source 'https://rubygems.org'

gem 'active_admin_import', '~> 4.0.0'
gem 'activeadmin', '~> 1.3.1'
gem 'ransack', '2.1.0'
gem 'activesupport'
gem 'bootstrap-sass', '~> 3.3', '>= 3.3.7'
gem 'cancancan'
gem 'coffee-rails', '~> 4.2'
gem 'combine_pdf', '~> 1.0.9'
gem 'concurrent-ruby', '~> 1.0.2'
gem 'devise', '~> 4.2'
gem 'faraday'
gem 'haml', '~> 4.0', '>= 4.0.7'
gem 'inherited_resources', '~> 1.9.0'
gem 'jbuilder', '~> 2.5'
gem 'jquery-rails'
gem 'json-schema', '~> 2.8.1'
gem 'oas_parser'
gem "paperclip", "~> 6.0.0"
gem 'pg', '~> 0.18'
gem 'puma', '~> 3.0'
gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
gem 'redis', '~> 4.0.0.rc1'
gem 'rollbar'
gem 'sass-rails', '~> 5.0'
gem 'savon', '~> 2.11', '>= 2.11.1'
gem 'swagger-docs', '~> 0.2.9'
gem 'swagger-parser'
gem 'turbolinks', '~> 5'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
gem 'uglifier', '>= 1.3.0'
gem 'virtual_keyboard', '~> 0.1.0'
gem 'activeadmin_addons'
gem 'staccato'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
  gem 'haml_lint'
  gem 'pry'
  gem 'pry-byebug'
  gem 'pry-doc'
  gem 'pry-rails'
  gem 'rubocop', '~> 0.50.0'
end

group :development do
  gem 'awesome_print'
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'listen', '~> 3.0.5'
  gem 'web-console'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'capybara-screenshot'
  gem 'minitest-rails-capybara', '~> 3.0.0'
  gem 'minitest-reporters'
  gem 'poltergeist'
  gem 'rails-controller-testing' # Allows assert_template & others
  gem 'vcr'
  gem 'webmock'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
