- name: "Create kiosk group"
  group:
    name: kiosk
    state: present

- name: "Create the sudo group"
  group:
    name: sudo
    state: present

- name: "Add kiosk user to totem"
  user:
    name: "{{ totem_linux_user }}"
    password: "{{ totem_linux_user_password }}"
    groups: sudo, {{ totem_linux_user }}
    append: yes
    state: present

